/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OfficialsPanel;

import classes.DataModel;
import connection.Connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Hector
 */
public class accountManagement extends javax.swing.JPanel {

  
    
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    private int kgID;
    
    public accountManagement() {
        initComponents();
       
       
        
        con = Connect.con();
        
        kgID = DataModel.getDatakgID();
        
      
     
       
    }

  
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jLabel1 = new javax.swing.JLabel();
        panelShadow1 = new swing.PanelShadow();
        jLabel4 = new javax.swing.JLabel();
        addOfficial_btn = new classes.Button();
        cpass = new classes.Passwordfeild();
        username_txt = new classes.Textfield();
        j = new javax.swing.JLabel();
        newPass = new classes.Passwordfeild();
        jLabel5 = new javax.swing.JLabel();
        pass1 = new classes.Passwordfeild();
        jLabel6 = new javax.swing.JLabel();
        showPass1 = new javax.swing.JCheckBox();
        shownewPass = new javax.swing.JCheckBox();
        showcPass = new javax.swing.JCheckBox();
        newusername_txt = new classes.Textfield();
        j1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 76, 76));
        jLabel1.setText("Manage Account");

        panelShadow1.setBackground(new java.awt.Color(202, 207, 210));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 55, 70));
        jLabel4.setText("Confirm Password");

        addOfficial_btn.setText("Save");
        addOfficial_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfficial_btnActionPerformed(evt);
            }
        });

        j.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        j.setForeground(new java.awt.Color(39, 55, 70));
        j.setText("Enter Username");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 55, 70));
        jLabel5.setText("Enter New Password");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 55, 70));
        jLabel6.setText("Enter Password");

        showPass1.setForeground(new java.awt.Color(255, 255, 255));
        showPass1.setText("Show Password");
        showPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPass1ActionPerformed(evt);
            }
        });

        shownewPass.setForeground(new java.awt.Color(255, 255, 255));
        shownewPass.setText("Show Password");
        shownewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shownewPassActionPerformed(evt);
            }
        });

        showcPass.setForeground(new java.awt.Color(255, 255, 255));
        showcPass.setText("Show Password");
        showcPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showcPassActionPerformed(evt);
            }
        });

        j1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        j1.setForeground(new java.awt.Color(39, 55, 70));
        j1.setText("Enter New Username");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addComponent(addOfficial_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPass1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelShadow1Layout.createSequentialGroup()
                        .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showcPass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPass, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(username_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpass, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shownewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newusername_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPass1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newusername_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shownewPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showcPass)
                .addGap(34, 34, 34)
                .addComponent(addOfficial_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addOfficial_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfficial_btnActionPerformed

        if (!username_txt.getText().isEmpty()) {
        if (!String.valueOf(pass1.getText()).isEmpty()) {
            
            String uname =  username_txt.getText();
            String pass = String.valueOf(pass1.getText());
                
            try {
                pst = con.prepareCall("SELECT * FROM officials_data WHERE username=? AND password=? AND brgy_off_id = ?;");
                pst.setString(1, uname);
                pst.setString(2, pass);
                pst.setInt(3, kgID);
                rs = pst.executeQuery();
                
                if (rs.next()) {
                    
                    if (!newusername_txt.getText().isEmpty()) {
                    if (!String.valueOf(newPass.getText()).isEmpty()) {
                    if (!String.valueOf(cpass.getText()).isEmpty()) {
                    if (new String(cpass.getPassword()).equals(new String(newPass.getPassword()))) {
                           
                        
                        String newUName = newusername_txt.getText();
                            String newpass = new String(cpass.getPassword());
                        
                        
                        try {
                            pst = con.prepareCall("UPDATE officials_data SET username = ? , password = ? WHERE brgy_off_id = ?");
                            pst.setString(1,newUName);
                            pst.setString(2,newpass);
                            pst.setInt(3,kgID);
                            pst.executeUpdate();
                            
                            JOptionPane.showMessageDialog(null, "Username and Password successfully change.");
                            
                            username_txt.setText("");
                            pass1.setText("");
                            newusername_txt.setText("");
                            newPass.setText("");
                            cpass.setText("");
                           
                            
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else {
                        
                         JOptionPane.showMessageDialog(null,"New Password and Confirm password doesnt match.");
                    }
                    } else {
                      JOptionPane.showMessageDialog(null,"Confirm Password is Empty.");
                    }
                    } else {
                      JOptionPane.showMessageDialog(null,"New Password is Empty.");
                    }
                    } else {
                      JOptionPane.showMessageDialog(null,"New username is Empty.");
                    }
                 
                     
                }else{
                
                JOptionPane.showMessageDialog(null, "Incorrect credentials.");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(accountManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
            
          
        } else {
            JOptionPane.showMessageDialog(null,"Password is empty.");
        }
        } else {
            JOptionPane.showMessageDialog(null,"Username is empty.");
        }
        
        
    }//GEN-LAST:event_addOfficial_btnActionPerformed

    private void showPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPass1ActionPerformed

        if(showPass1.isSelected()){
            pass1.setEchoChar('\0');
        }else{
            pass1.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_showPass1ActionPerformed

    private void shownewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shownewPassActionPerformed
        // TODO add your handling code here:
            if(shownewPass.isSelected()){
            newPass.setEchoChar('\0');
        }else{
            newPass.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_shownewPassActionPerformed

    private void showcPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showcPassActionPerformed
        // TODO add your handling code here:
           if(showcPass.isSelected()){
            cpass.setEchoChar('\0');
        }else{
            cpass.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_showcPassActionPerformed

//    private void deleteUserAaccount(){
//
// int selectedRow = tableAccounts.getSelectedRow();
//
//              
//                    // Extract information from the selected row
//                    int userId = (int) tableAccounts.getValueAt(selectedRow, 0);
//
//                    // Construct the SQL DELETE statement
//                    String sql = "DELETE FROM brgy_officials WHERE id = ?";
//
//                    try (PreparedStatement statement = con.prepareStatement(sql)) {
//                        // Set the parameter in the DELETE statement
//                        statement.setInt(1, userId);
//
//                        // Execute the DELETE statement
//                        statement.executeUpdate();
//
//                        // Remove the selected row from the JTable model
//                        DefaultTableModel model = (DefaultTableModel) tableAccounts.getModel();
//                        model.removeRow(selectedRow);
//
//                      
//                       
//                    
//                    } catch (SQLException ex) {
//                        Logger.getLogger(accountManagement.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//
//
//
//}
//    
//    
//    //load database
//    private void loadDatafromDataBase(){
//     
//      
//         
//         DefaultTableModel model = (DefaultTableModel) tableAccounts.getModel();
//         model.setRowCount(0);
//         
//         try {
//            pst = con.prepareCall("SELECT brgy_officials.Id, brgy_officials.Name, officials_data.username, officials_data.password FROM brgy_officials "
//                    + "INNER JOIN officials_data ON brgy_officials.id = officials_data.brgy_off_id; ");
//            rs = pst.executeQuery();
//            
//            while(rs.next()){
//            Object[] rowdata = new Object[4];
//            
//            for(int i = 0; i < 4; i++){
//            
//                rowdata[i] =rs.getObject(i+1);
//            
//            }
//            tableAccounts.addRow(rowdata);
//            
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(accountManagement.class.getName()).log(Level.SEVERE, null, ex);
//        }
//         
//     }
//    
//    
//    
// private int NextIdFromDatabase() {
//    int nextId = 0;
//
//    try {
//        // Get the auto-increment value for the table
//        Statement stmt = con.createStatement();
//        ResultSet rs = stmt.executeQuery("SHOW TABLE STATUS LIKE 'brgy_officials'");
//        
//        if (rs.next()) {
//            nextId = rs.getInt("Auto_increment");
//        }
//
//        stmt.close();
//    } catch (SQLException ex) {
//        Logger.getLogger(accountManagement.class.getName()).log(Level.SEVERE, null, ex);
//    }
//
//    return nextId;
//}    
// 
 

 
 
 //update table
 
 private void updateOfficial(int id, String usrname, String pass) {
  
       
        String sql1 = "UPDATE `officials_data` SET  `username` = ?, `password` = ? WHERE `brgy_off_id` = ?";
        
        
        
        try {
            pst = con.prepareCall(sql1);
            pst.setString(1, usrname);
            pst.setString(2, pass);
            pst.setInt(3, id);
            pst.executeUpdate();
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(accountManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
}
 
 
 
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classes.Button addOfficial_btn;
    private classes.Passwordfeild cpass;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JLabel j;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private classes.Passwordfeild newPass;
    private classes.Textfield newusername_txt;
    private swing.PanelShadow panelShadow1;
    private classes.Passwordfeild pass1;
    private javax.swing.JCheckBox showPass1;
    private javax.swing.JCheckBox showcPass;
    private javax.swing.JCheckBox shownewPass;
    private classes.Textfield username_txt;
    // End of variables declaration//GEN-END:variables
}
