/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package superAdminPanel;

import connection.Connect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hector
 */
public class addPurok extends javax.swing.JFrame {

  
        
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public addPurok() {
        initComponents();
        init();
        con =  Connect.con();
        
        
        
        
        try {
            pst = con.prepareCall("SELECT name From brgy_officials WHERE position = \"Kagawad\";");
            rs = pst.executeQuery();
            
            while (rs.next()) {                
                String name = rs.getString("name");
                kgAssigned_Cbox.addItem(name);
                
            }
            
        } catch (Exception e) {
        }
        
        int p_ID = NextIdFromDatabase();
        purokID_txt.setText(String.valueOf(p_ID));
        
    }

    
    
    
       public  void init(){
    
        setBackground(new Color(0,0,0,0));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new swing.PanelShadow();
        addPurok_btn = new classes.Button();
        kgAssigned_Cbox = new classes.ComboBox();
        jLabel5 = new javax.swing.JLabel();
        purokName_txt = new classes.Textfield();
        jLabel3 = new javax.swing.JLabel();
        purokNo_txt = new classes.Textfield();
        jLabel2 = new javax.swing.JLabel();
        close_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        purokID_txt = new classes.Textfield();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        addPurok_btn.setText("Add");
        addPurok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPurok_btnActionPerformed(evt);
            }
        });

        kgAssigned_Cbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        kgAssigned_Cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kgAssigned_CboxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 55, 70));
        jLabel5.setText("Kagawad Assigned");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 55, 70));
        jLabel3.setText("Purok Name");

        purokNo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purokNo_txtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 55, 70));
        jLabel2.setText("Purok Number");

        close_lbl.setBackground(new java.awt.Color(231, 76, 60));
        close_lbl.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        close_lbl.setForeground(new java.awt.Color(255, 255, 255));
        close_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_lbl.setText("X");
        close_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_lblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                close_lblMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 55, 70));
        jLabel4.setText("Purok ID");

        purokID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purokID_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(close_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                        .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kgAssigned_Cbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(purokName_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelShadow1Layout.createSequentialGroup()
                                        .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(purokNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(panelShadow1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(160, 160, 160)))
                            .addComponent(addPurok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(panelShadow1Layout.createSequentialGroup()
                        .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(purokID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(close_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purokID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(purokNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purokName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kgAssigned_Cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPurok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelShadow1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addPurok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPurok_btnActionPerformed

       
        if (!purokNo_txt.getText().isEmpty()) {
            if (!purokName_txt.getText().isEmpty()) {
            if (!kgAssigned_Cbox.getSelectedItem().equals("Select")) {

                
                int purokNo = Integer.parseInt(purokNo_txt.getText());
                String purokName = purokName_txt.getText();
                String kgName = kgAssigned_Cbox.getSelectedItem().toString();
                int p_ID = Integer.parseInt(purokID_txt.getText());
                
                
                insertPurok(purokNo, purokName, p_ID, kgName);
                addPurok adp = new addPurok();
                adp.dispose();
               
                
                
            } else {
                 JOptionPane.showMessageDialog(null, "Please select Kagawad.");
        } 
            } else {
                 JOptionPane.showMessageDialog(null, "Purok name is empty.");
        } 
        }else {
            JOptionPane.showMessageDialog(null, "Purok no. is empty.");
        }
        
    }//GEN-LAST:event_addPurok_btnActionPerformed

    private void kgAssigned_CboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kgAssigned_CboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kgAssigned_CboxActionPerformed

    private void purokNo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purokNo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purokNo_txtActionPerformed

    private void close_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lblMouseEntered

        close_lbl.setForeground(new Color(231, 76, 60));
    }//GEN-LAST:event_close_lblMouseEntered

    private void close_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lblMouseExited

        close_lbl.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_close_lblMouseExited

    private void close_lblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lblMousePressed

       this.dispose();
    }//GEN-LAST:event_close_lblMousePressed

    private void purokID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purokID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purokID_txtActionPerformed

    
        
 private void insertPurok(int purok_no, String purok_name, int id, String kg_name) {
    String sql = "INSERT INTO `purok` ( `purok_no`,`purok_name`) VALUES (?,?)" ;
    try (PreparedStatement statement = con.prepareStatement(sql)) {
        statement.setInt(1, purok_no);
        statement.setString(2, purok_name);
        statement.executeUpdate();
        
       
        
        
       try{ pst = con.prepareCall("UPDATE `brgy_officials` SET `purok_assigned` = ? WHERE `Name` = ?");
          pst.setInt(1, id);
          pst.setString(2, kg_name);
          pst.executeUpdate();
      
      
      
       
            
        
        } catch (SQLException ex) {
            Logger.getLogger(manageHousehold.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    } catch (SQLException ex) {
        Logger.getLogger(manageHousehold.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    
    
    private int NextIdFromDatabase() {
    int nextId = 0;

    try {
        // Get the auto-increment value for the table
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("SHOW TABLE STATUS LIKE 'purok'");
        
        if (rs.next()) {
            nextId = rs.getInt("Auto_increment");
        }

        stmt.close();
    } catch (SQLException ex) {
        Logger.getLogger(accountManagement.class.getName()).log(Level.SEVERE, null, ex);
    }

    return nextId;
}    
    
     
      
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addPurok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addPurok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addPurok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addPurok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addPurok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classes.Button addPurok_btn;
    private javax.swing.JLabel close_lbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private classes.ComboBox kgAssigned_Cbox;
    private swing.PanelShadow panelShadow1;
    private classes.Textfield purokID_txt;
    private classes.Textfield purokName_txt;
    private classes.Textfield purokNo_txt;
    // End of variables declaration//GEN-END:variables
}
