/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package superAdminPanel;

import classes.DataModel;
import classes.tablActionCellRenderer;
import classes.tablActionCellRendererView;
import classes.tableActionCellEditor;
import classes.tableActionCellEditorView;
import classes.tableActionEvent;
import classes.tableActionEvent1;
import classes.tableActionEventView;
import connection.Connect;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hector
 */
public class officailsPanel extends javax.swing.JPanel {

   
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public officailsPanel() {
        initComponents();
        con = Connect.con();
        
        
       tableActionEventView event = new tableActionEventView() {
            @Override
            public void onView(int row) {
              
                   int selectedrow  =table_off.getSelectedRow();
              
             if (selectedrow != -1) {
               
                   Object value = table_off.getValueAt(selectedrow, 0);
                        if (value != null) {
                          String nameOFF = value.toString();
                           
                           
                             try {
                    pst = con.prepareCall("Select Id From brgy_officials where Name = ? ");
                    pst.setString(1, nameOFF);
                    rs = pst.executeQuery();
                    
                                 if (rs.next()) {
                                     int offID = rs.getInt("Id");
                                     DataModel.setDataoffID(offID);
                                     
                                     officialData offdata = new officialData();
                                     offdata.show();
                
                                     
                                 }
                    
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                
                
                           
                           
                        }
             }
              
                 }


        };
        
                
        table_off.getColumnModel().getColumn(3).setCellRenderer(new tablActionCellRendererView() );
        table_off.getColumnModel().getColumn(3).setCellEditor(new tableActionCellEditorView(event) );
       
        displayImageTable();
    }

     public void displayImageTable() {
        try {
            pst= con.prepareCall("SELECT brgy_officials.name, brgy_officials.Position, officials_data.image FROM brgy_officials " +
"                INNER JOIN officials_data ON brgy_officials.id = officials_data.brgy_off_id");
            rs = pst.executeQuery();

            
            while (rs.next()) {
        Object[] rowdata = new Object[3];

        for (int i = 0; i < 3; i++) {
            rowdata[i] = rs.getObject(i + 1);
        }

        // Get the image data from the result set
        byte[] imageData = rs.getBytes("image");

        // Create an ImageIcon from the image data
        ImageIcon imageIcon = new ImageIcon(imageData);
         Image img = imageIcon.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH);
         

        // Set the image icon in the last column of the row data
        rowdata[2] = new ImageIcon(img);

        table_off.addRow(rowdata);
    }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        button2 = new classes.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_off = new classes.Table1();
        button1 = new classes.Button();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BARANGAY OFFICIALS");

        button2.setBackground(new java.awt.Color(0, 174, 27));
        button2.setText("Manage Official");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        table_off.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Position", "Image", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_off.setRowHeight(90);
        jScrollPane1.setViewportView(table_off);

        button1.setBackground(new java.awt.Color(255, 153, 0));
        button1.setText("Refresh");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1077, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
       
        manageOfficial mOfficial = new manageOfficial();
        mOfficial.show();
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       
        
         DefaultTableModel model = (DefaultTableModel) table_off.getModel();
         model.setRowCount(0);
         
         
         displayImageTable();
         
        
//             try {
//            pst = con.prepareCall("SELECT brgy_officials.name, brgy_officials.Position, officials_data.image FROM brgy_officials " +
//"                INNER JOIN officials_data ON brgy_officials.id = officials_data.brgy_off_id");
//            rs = pst.executeQuery();
//            
//            while(rs.next()){
//            Object[] rowdata = new Object[3];
//            
//            for(int i = 0; i < 3; i++){
//            
//                rowdata[i] =rs.getObject(i+1);
//            
//            }
//            table_off.addRow(rowdata);
//            
//            }
//            
//        } catch (SQLException ex) {  
//            Logger.getLogger(dashboardPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_button1ActionPerformed

    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classes.Button button1;
    private classes.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private classes.Table1 table_off;
    // End of variables declaration//GEN-END:variables
}
