/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package superAdminPanel;

import classes.ScrollBar;
import classes.tablActionCellRenderer;
import classes.tableActionCellEditor;
import classes.tableActionEvent;
import connection.Connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hector
 */
public class purokManagement extends javax.swing.JPanel {

      
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
     
    
    public purokManagement() {
        initComponents();
        con = Connect.con();
        
        tablePurok_scroll.setVerticalScrollBar(new ScrollBar());
        
          tableActionEvent event = new tableActionEvent() {
            @Override
            public void onEdit(int row) {
                System.out.println("EDIT ROW: " + row);
                 }

            @Override
            public void onDelete(int row) {
              
                if (table_purok.isEditing()) {
                    table_purok.getCellEditor().stopCellEditing();
                }
               deleteTablePurok();
            }
        };
                
          
             try {
            pst = con.prepareCall("SELECT purok.id,purok.purok_no, purok.purok_name,brgy_officials.Name FROM purok "
                    + "INNER JOIN brgy_officials WHERE brgy_officials.purok_assigned = purok.id; ");
            rs = pst.executeQuery();
            
            while(rs.next()){
            Object[] rowdata = new Object[4];
            
            for(int i = 0; i < 4; i++){
            
                rowdata[i] =rs.getObject(i+1);
            
            }
            table_purok.addRow(rowdata);
            
            }
            
        } catch (SQLException ex) {  
            Logger.getLogger(dashboardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
          
          
          
                
        table_purok.getColumnModel().getColumn(4).setCellRenderer(new tablActionCellRenderer() );
        table_purok.getColumnModel().getColumn(4).setCellEditor(new tableActionCellEditor(event) );
    }

    
    private void deleteTablePurok(){

 int selectedRow = table_purok.getSelectedRow();

              
                    // Extract information from the selected row
                    int userId = (int) table_purok.getValueAt(selectedRow, 0);

                    // Construct the SQL DELETE statement
                    String sql = "DELETE FROM purok WHERE id = ?";

                    try (PreparedStatement statement = con.prepareStatement(sql)) {
                        // Set the parameter in the DELETE statement
                        statement.setInt(1, userId);

                        // Execute the DELETE statement
                        statement.executeUpdate();

                        // Remove the selected row from the JTable model
                        DefaultTableModel model = (DefaultTableModel) table_purok.getModel();
                        model.removeRow(selectedRow);

                      
                       
                    
                    } catch (SQLException ex) {
                        Logger.getLogger(OfficialsPanel.accountManagement.class.getName()).log(Level.SEVERE, null, ex);
                    }



}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tablePurok_scroll = new javax.swing.JScrollPane();
        table_purok = new classes.Table();
        jLabel4 = new javax.swing.JLabel();
        addPurok_btn = new classes.Button();
        addPurok_btn1 = new classes.Button();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PUROK MANAGEMENT");

        table_purok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purok ID", "Purok No.", "Purok Name", "Official Assigned", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePurok_scroll.setViewportView(table_purok);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 76, 76));
        jLabel4.setText("List of Purok");

        addPurok_btn.setText("Add Purok");
        addPurok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPurok_btnActionPerformed(evt);
            }
        });

        addPurok_btn1.setBackground(new java.awt.Color(245, 157, 30));
        addPurok_btn1.setText("Refresh");
        addPurok_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPurok_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(795, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPurok_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addPurok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tablePurok_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPurok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addPurok_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePurok_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPurok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPurok_btnActionPerformed

    addPurok ADDpurok = new addPurok();
    ADDpurok.show();

    }//GEN-LAST:event_addPurok_btnActionPerformed

    
    
    
    
    private void addPurok_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPurok_btn1ActionPerformed
        
         DefaultTableModel model = (DefaultTableModel) table_purok.getModel();
         model.setRowCount(0);
        
             try {
            pst = con.prepareCall("SELECT purok.id,purok.purok_no, purok.purok_name,brgy_officials.Name FROM purok "
                    + "INNER JOIN brgy_officials WHERE brgy_officials.purok_assigned = purok.id; ");
            rs = pst.executeQuery();
            
            while(rs.next()){
            Object[] rowdata = new Object[4];
            
            for(int i = 0; i < 4; i++){
            
                rowdata[i] =rs.getObject(i+1);
            
            }
            table_purok.addRow(rowdata);
            
            }
            
        } catch (SQLException ex) {  
            Logger.getLogger(dashboardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addPurok_btn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classes.Button addPurok_btn;
    private classes.Button addPurok_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane tablePurok_scroll;
    private classes.Table table_purok;
    // End of variables declaration//GEN-END:variables
}
